framework:
    asset_mapper:
        importmap_polyfill: false
        # The paths to make available to the asset mapper.
        paths:
            - assets
            - vendor/tempest/highlight/src/Themes/Css
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
