framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        # https://symfony.com/doc/current/messenger.html#transport-configuration
        transports:
            sync: 'sync://'

        routing:
            'App\Shared\Domain\ObjectMapper\Command\MapObject': sync
            'App\Places\Domain\Command\CreatePlace': sync
            'App\Places\Domain\Command\CreateAddress': sync

        buses:
            messenger.bus.default: ~
            messenger.bus.command:
                middleware:
                    - validation
                    # each time a message is handled, the Doctrine connection
                    # is "pinged" and reconnected if it's closed. Useful
                    # if your workers run for a long time and the database
                    # connection is sometimes lost
                    - doctrine_ping_connection
                    # commit or rollback transactions automatically. Useful for ACID
                    - doctrine_transaction

        default_bus: messenger.bus.default
        
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
