twig:
    file_name_pattern: '*.twig'
    globals:
        GOOGLE_PLACES_PRIVATE_API_KEY: '%env(GOOGLE_PLACES_PRIVATE_API_KEY)%'
        SOURCE_COMMIT: '%env(SOURCE_COMMIT)%'

when@test:
    twig:
        strict_variables: true
