twig_component:
    #anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Blog\Infrastructure\Symfony\Twig\Components\:
            template_directory: 'components/Blog/'
            name_prefix: Blog
        App\Shared\Twig\Components\: 'components/'
