twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        App\Shared\Application\Twig\Components\: 'components/'
        App\Blog\Infrastructure\Twig\Components\:
            template_directory: 'components/Blog/'
            name_prefix: Blog
