services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      SERVER_NAME: ${SERVER_NAME}
      DATABASE_URL: ${DATABASE_URL}
      APP_DEFAULT_URI: ${APP_DEFAULT_URI}
      HTTP_CACHE_ADAPTER: ${HTTP_CACHE_ADAPTER}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_ZONE_ID: ${CLOUDFLARE_ZONE_ID}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      REDIS_URL: ${REDIS_URL}
      GOOGLE_PLACES_PRIVATE_API_KEY: ${GOOGLE_PLACES_PRIVATE_API_KEY}

    volumes:
      - ./var/storage:/app/var/storage:rw

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data:rw
#  valkey:
#    image: valkey/valkey:7.2-alpine
#    volumes:
#      - ./docker/valkey/data:/data:rw
