services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  redis:
    image: 'redis:alpine'
    ports: [6379]
    volumes:
      - redis_data:/data:rw
  #valkey:
  #  image: valkey/valkey:latest
  #  volumes:
  #    - valkey_data:/data:rw

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
  redis_data:
  valkey_data:
###< doctrine/doctrine-bundle ###
