<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241008201203 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Change ORM\GeneratedValue strategy to IDENTITY';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE blog_post ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE blog_post ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE blog_post ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN blog_post.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN blog_post.updated_at IS \'\'');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER start_date TYPE DATE');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER end_date TYPE DATE');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN cv_professional_experience.start_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN cv_professional_experience.end_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN cv_professional_experience.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN cv_professional_experience.updated_at IS \'\'');
        $this->addSql('ALTER TABLE cv_project ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE cv_project ALTER date TYPE DATE');
        $this->addSql('ALTER TABLE cv_project ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cv_project ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN cv_project.date IS \'\'');
        $this->addSql('COMMENT ON COLUMN cv_project.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN cv_project.updated_at IS \'\'');
        $this->addSql('ALTER TABLE place ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE place ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE place ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN place.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN place.updated_at IS \'\'');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE cv_project ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cv_project ALTER date TYPE DATE');
        $this->addSql('ALTER TABLE cv_project ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cv_project ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN cv_project.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cv_project.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cv_project.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE place ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE place ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE place ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN place.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN place.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER start_date TYPE DATE');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER end_date TYPE DATE');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cv_professional_experience ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN cv_professional_experience.start_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cv_professional_experience.end_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cv_professional_experience.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cv_professional_experience.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE blog_post ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE blog_post ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE blog_post ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN blog_post.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN blog_post.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
