<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260830150837 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CV: move job_name/description/badges (experience) and description (project) into per-locale translation tables (existing content becomes the "fr" translation)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cv_professional_experience_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(5) NOT NULL, job_name VARCHAR(255) NOT NULL, description TEXT NOT NULL, badges JSONB NOT NULL, experience_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DDAB983B46E90E27 ON cv_professional_experience_translation (experience_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DDAB983B46E90E274180C698 ON cv_professional_experience_translation (experience_id, locale)');
        $this->addSql('CREATE TABLE cv_project_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(5) NOT NULL, description TEXT NOT NULL, project_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_27FD24E166D1F9C ON cv_project_translation (project_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_27FD24E166D1F9C4180C698 ON cv_project_translation (project_id, locale)');
        $this->addSql('ALTER TABLE cv_professional_experience_translation ADD CONSTRAINT FK_DDAB983B46E90E27 FOREIGN KEY (experience_id) REFERENCES cv_professional_experience (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_project_translation ADD CONSTRAINT FK_27FD24E166D1F9C FOREIGN KEY (project_id) REFERENCES cv_project (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("INSERT INTO cv_professional_experience_translation (locale, job_name, description, badges, experience_id) SELECT 'fr', job_name, description, badges, id FROM cv_professional_experience");
        $this->addSql("INSERT INTO cv_project_translation (locale, description, project_id) SELECT 'fr', description, id FROM cv_project");

        $this->addSql('ALTER TABLE cv_professional_experience DROP job_name');
        $this->addSql('ALTER TABLE cv_professional_experience DROP description');
        $this->addSql('ALTER TABLE cv_professional_experience DROP badges');
        $this->addSql('ALTER TABLE cv_project DROP description');
    }

    public function down(Schema $schema): void
    {
        $this->addSql("ALTER TABLE cv_professional_experience ADD job_name VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE cv_professional_experience ADD description TEXT DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE cv_professional_experience ADD badges JSONB DEFAULT '[]' NOT NULL");
        $this->addSql("ALTER TABLE cv_project ADD description TEXT DEFAULT '' NOT NULL");

        $this->addSql("UPDATE cv_professional_experience e SET job_name = t.job_name, description = t.description, badges = t.badges FROM cv_professional_experience_translation t WHERE t.experience_id = e.id AND t.locale = 'fr'");
        $this->addSql("UPDATE cv_project p SET description = t.description FROM cv_project_translation t WHERE t.project_id = p.id AND t.locale = 'fr'");

        $this->addSql('ALTER TABLE cv_professional_experience_translation DROP CONSTRAINT FK_DDAB983B46E90E27');
        $this->addSql('ALTER TABLE cv_project_translation DROP CONSTRAINT FK_27FD24E166D1F9C');
        $this->addSql('DROP TABLE cv_professional_experience_translation');
        $this->addSql('DROP TABLE cv_project_translation');
    }
}
