controllers_shared:
    resource:
        path: ../src/Shared/Infrastructure/
        namespace: App\Shared\Infrastructure
    type: attribute
    
controllers_user:
    resource:
        path: ../src/User/Infrastructure/Symfony/Controller/
        namespace: App\User\Infrastructure\Symfony\Controller
    type: attribute

controllers_blog:
    resource:
        path: ../src/Blog/Infrastructure/Symfony/Controller/
        namespace: App\Blog\Infrastructure\Symfony\Controller
    type: attribute

controllers_cv:
    resource:
        path: ../src/CV/Infrastructure/Symfony/Controller/
        namespace: App\CV\Infrastructure\Symfony\Controller
    type: attribute

controllers_places:
    resource:
        path: ../src/Places/Infrastructure/Symfony/Controller/
        namespace: App\Places\Infrastructure\Symfony\Controller
    type: attribute

